Models/Department.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace asp.netDay2.Models;

public partial class Department
{
    public int DeptId { get; set; }
    [StringLength(50, MinimumLength = 2)]
    [Required(ErrorMessage = "Name is required")]
    public string? DeptName { get; set; }
    
    [Required(ErrorMessage = "describtion is required")]
    public string? DeptDesc { get; set; }
    
    [Required(ErrorMessage = "location is required")]
    public string? DeptLocation { get; set; }

    public int? DeptManager { get; set; }

    public DateOnly? ManagerHiredate { get; set; }

    public virtual Instructor? DeptManagerNavigation { get; set; }

    public virtual ICollection<Instructor> Instructors { get; set; } = new List<Instructor>();

    public virtual ICollection<Student> Students { get; set; } = new List<Student>();
}

Controllers/DepartmentController.cs
using asp.netDay2.Models;
using asp.netDay2.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace asp.netDay2.Controllers
{    
    public class DepartmentController : Controller
    {

        private readonly ItiContext itiContext;
        public DepartmentController(ItiContext Context)
        {
            itiContext = Context;
        }
        public IActionResult Index()
        {
            ICollection<Department> departments = itiContext.Departments.Take(100).ToList();
            return View(departments);
        }
        public IActionResult Details(int id)
        {
            var department = itiContext.Departments.Where(d => d.DeptId == id).FirstOrDefault();
            //var Top = course.Top;
            DepartmentVM DptVM = new DepartmentVM()
            {
                DeptName = department.DeptName,
                DeptLocation = department.DeptLocation,                
            };
            itiContext.SaveChanges();
            return View(DptVM);
        }

        public IActionResult Create()
        {
            // return the create view to enter data
            return View();
        }
        [HttpPost]
        public IActionResult Save(Department Dept)
        {
            if (ModelState.IsValid)
            {

                // create new instructor using context
                itiContext.Departments.Add(Dept);
                itiContext.SaveChanges();
            }
            return RedirectToAction("index");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var currentDept = itiContext.Departments.Where(d => d.DeptId == id).FirstOrDefault();
            return View(currentDept);
        }

        [HttpPost]
        public IActionResult Edit(Department Department)
        {
            var currentDept = itiContext.Departments.Where(d => d.DeptId == Department.DeptId).FirstOrDefault();
            currentDept.DeptName = Department.DeptName;
            currentDept.DeptDesc = Department.DeptDesc;
            currentDept.DeptManager = Department.DeptManager;
            currentDept.DeptLocation = Department.DeptLocation;
            itiContext.SaveChanges();
            return RedirectToAction("index");
        }

        public ActionResult delete(int id)
        {
            var currentDept = itiContext.Departments.Where(d => d.DeptId == id).FirstOrDefault();
            
            if (currentDept != null)
            {
                
                var insDept = itiContext.Instructors.Where(c => c.DeptId == id);
                var inscrs = itiContext.InsCourses.Where(c => insDept.Any(d => d.InsId == c.InsId));                
                
                // remove ins_courses for this department
                itiContext.Instructors.RemoveRange(insDept);
                //itiContext.Students.RemoveRange(studentDept);
                itiContext.InsCourses.RemoveRange(inscrs);
                itiContext.Departments.RemoveRange(currentDept);
                itiContext.SaveChanges();
            }
            return RedirectToAction("index");

        }

    }
}

Views/Department/Create.cshtml
@model asp.netDay2.Models.Department

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Topic</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body style="background-image:url('https://wallpapercave.com/wp/wp6684577.jpg');
   background-size: cover; background-position: center; background-repeat: no-repeat;">
    <div class="container mt-4">
        <div class="row justify-content-center">
            <div class="col-md-5">

                <h3 class="text-center" style="color:azure;">Create new Department</h3>
                <hr style="color:aliceblue" />
                        <form class="px-md-2" asp-controller="department" asp-action="save" method="post">

                            <div data-mdb-input-init class="form-outline mb-4">                               
                                @Html.LabelFor(n => n.DeptId, new { @class = "form-label", style = "color: white;" })
                                @Html.TextBoxFor(n => n.DeptId, new { @class = "form-control" })
                                @Html.ValidationMessageFor(n => n.DeptId, "", new { @class = "text-danger" })
                            </div>
                            <div data-mdb-input-init class="form-outline mb-4">
                                @Html.LabelFor(n => n.DeptName, new { @class = "form-label", style = "color: white;" })
                                @Html.TextBoxFor(n => n.DeptName, new { @class = "form-control" })
                                @Html.ValidationMessageFor(n => n.DeptName, "", new { @class = "text-danger" })
                            </div>
                            <div data-mdb-input-init class="form-outline mb-4">
                                @Html.LabelFor(n => n.DeptDesc, new { @class = "form-label", style = "color: white;" })
                                @Html.TextBoxFor(n => n.DeptDesc, new { @class = "form-control" })
                                @Html.ValidationMessageFor(n => n.DeptDesc, "", new { @class = "text-danger" })
                            </div>
                            <div data-mdb-input-init class="form-outline mb-4">
                                @Html.LabelFor(n => n.DeptLocation, new { @class = "form-label", style = "color: white;" })
                                @Html.TextBoxFor(n => n.DeptLocation, new { @class = "form-control" })
                                @Html.ValidationMessageFor(n => n.DeptLocation, "", new { @class = "text-danger" })
                            </div>
                            <div data-mdb-input-init class="form-outline mb-4">
                                @Html.LabelFor(n => n.DeptManager, new { @class = "form-label", style = "color: white;" })
                                @Html.TextBoxFor(n => n.DeptManager, new { @class = "form-control" })
                                @Html.ValidationMessageFor(n => n.DeptManager, "", new { @class = "text-danger" })
                            </div>
                            <div data-mdb-input-init class="form-outline mb-4">
                                @Html.LabelFor(n => n.ManagerHiredate, new { @class = "form-label", style = "color: white;" })
                                @Html.TextBoxFor(n => n.ManagerHiredate, new { @class = "form-control" })
                                @Html.ValidationMessageFor(n => n.ManagerHiredate, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group text-center mt-4">
                        <input type="submit" value="Submit" class="btn btn-success" />
                    </div>
                    
                        </form>
                <div class="text-center mt-3">
                    <a asp-action="Index" style="color:azure;font-size:large ;font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif">Back to List</a>
                </div>
            </div>
        </div>
    </div>

<script src="/lib/jquery/dist/jquery.min.js"></script>
<script src="/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
</body>
</html>

Views/Department/Details.cshtml
@model asp.netDay2.ViewModel.DepartmentVM
<h1>Details</h1>
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-M3PWQaY2QFIhwuzE7VW3K1dyA0C1coQemlJD1qDzWIxmg4zFMEu50eU/HiPzGmG4" crossorigin="anonymous">
</head>
<table class="table table-striped">
    <tr style="background-color:black">
        <th style="color:azure">DeptName</th>
        <th style="color:azure">DeptLocation</th>
    </tr>
    <tr>
        <td>@Model.DeptName</td>
        <td>@Model.DeptLocation</td>        
    </tr>
</table>


<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgvVh5lB7Cji8gk54A1hohzTYfJr8Hd50Tvf6Ezri0fxYSl0pGr" crossorigin="anonymous"></script>

Views/Department/Edit.cshtml
@model asp.netDay2.Models.Department
@{
    var Department = Model;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Department</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body style="background-image:url('https://wallpapercave.com/wp/wp6684577.jpg');
   background-size: cover; background-position: center; background-repeat: no-repeat;">
<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-5">
                <h1 class="text-center" style="color:azure;">Edit</h1>
                <h4 class="text-center" style="color:azure;">Department</h4>
                <hr style="color:aliceblue" />
            <form asp-controller="department" asp-action="edit" method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="DeptId" />
                <div class="form-group">
                    <label asp-for="DeptName" class="control-label" style="color:azure; font-size:large; font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif"></label>
                    <input asp-for="DeptName" class="form-control" />
                    <span asp-validation-for="DeptName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="DeptDesc" class="control-label" style="color:azure; font-size:large; font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif"></label>
                    <input asp-for="DeptDesc" class="form-control" />
                    <span asp-validation-for="DeptDesc" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="DeptLocation" class="control-label" style="color:azure; font-size:large; font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif"></label>
                    <input asp-for="DeptLocation" class="form-control" />
                    <span asp-validation-for="DeptLocation" class="text-danger"></span>
                </div>
                <div class="form-group text-center mt-4">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
            </form>
            <div class="text-center mt-3 ">
                    <a asp-action="Index" style=" color:azure;font-size:large ;font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif">Back to List</a>
            </div>
        </div>
    </div>
</div>
<script src="/lib/jquery/dist/jquery.min.js"></script>
<script src="/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
</body>
</html>

Views/Department/Index.cshtml
@model ICollection<asp.netDay2.Models.Department>
@* @{
    ViewBag.Title = "Home Page";
    Layout = "~/Views/Shared/_mylayout.cshtml";
} *@
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-M3PWQaY2QFIhwuzE7VW3K1dyA0C1coQemlJD1qDzWIxmg4zFMEu50eU/HiPzGmG4" crossorigin="anonymous">
</head>


    <table class="table table-striped" style="margin-top:20px">
    <thead>
        <tr style="background-color:black">
            <th style="color:azure">
                DeptID
            </th>
            <th style="color:azure">
                DeptName
            </th>
            <th style="color:azure">
                DeptDesc
            </th>
            <th style="color:azure">
                DeptLocation
            </th>            
            <th style="color:azure">
                ManagerHiredate
            </th>
            <th style="color:azure">
                Details
            </th>
            <th style="color:azure">
                Edit
            </th>
            <th style="color:azure">
                Delete
            </th>
        </tr>

    </thead>
    <tbody>
        @foreach (var dept in Model)
        {
            <tr>
                <td>
                    @dept.DeptId
                </td>
                <td>
                    @dept.DeptName
                </td>
                <td>
                    @dept.DeptDesc
                </td>
                <td>
                    @dept.DeptLocation
                </td>               
                <td>
                    @dept.ManagerHiredate
                </td>
                <td>
                    <form asp-controller="department" asp-action="details" asp-route-id="@dept.DeptId" method="post">
                        <button  class="btn btn-info">details</button>
                    </form>
                </td>
                <td>
                    <form asp-controller="department" asp-action="edit" asp-route-id="@dept.DeptId" method="get">
                        <button  class="btn btn-primary">Edit</button>
                    </form>
                </td>
                    <td>
                        <!-- Button trigger modal -->
                        <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal"
                                data-department-id="@dept.DeptId">
                            Delete
                        </button>

                        <!-- Modal -->
                        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel">Confirm Deletion</h5>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        Are you sure you want to delete this department?
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No</button>
                                        <form id="deleteForm" asp-controller="Department" asp-action="Delete" method="post">
                                            <!-- Hidden field to hold the department ID -->
                                            <input type="hidden" name="id" id="modalDepartmentId">
                                            <button type="submit" class="btn btn-primary">Yes</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </td>

                    <script>
                        // JavaScript to set the department ID in the modal form when the delete button is clicked
                        document.addEventListener('DOMContentLoaded', function () {
                            var deleteButtons = document.querySelectorAll('[data-bs-toggle="modal"]');
                            deleteButtons.forEach(function (button) {
                                button.addEventListener('click', function () {
                                    var departmentId = this.getAttribute('data-department-id');
                                    document.getElementById('modalDepartmentId').value = departmentId;
                                });
                            });
                        });
                    </script>
            </tr>
        }

    </tbody>
    
</table>
    <form action="/department/create" method="post">
        <button class="btn btn-outline-primary btn-rounded" data-mdb-ripple-init data-mdb-ripple-color="dark">Create New Department</button>
    </form>

-
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgvVh5lB7Cji8gk54A1hohzTYfJr8Hd50Tvf6Ezri0fxYSl0pGr" crossorigin="anonymous"></script>