Models/Instructor.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace asp.netDay2.Models;

public partial class Instructor
{
    
    public int InsId { get; set; }
    [StringLength(50, MinimumLength = 2)]
    [Required(ErrorMessage = "Name is required")]
    public string? InsName { get; set; }
    [Required]
    public string? InsDegree { get; set; }
    [Range(4000, 9000, ErrorMessage = "salary must be between 4000 and 9000")]
    [Required]
    public decimal? Salary { get; set; }
    
    public int? DeptId { get; set; }

    public virtual ICollection<Department> Departments { get; set; } = new List<Department>();

    public virtual Department? Dept { get; set; }

    public virtual ICollection<InsCourse> InsCourses { get; set; } = new List<InsCourse>();
}

Controllers/InstructorController.cs
using asp.netDay2.Models;
using asp.netDay2.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Net;

namespace asp.netDay2.Controllers
{
    public class InstructorController : Controller
    {
        private readonly ItiContext itiContext;
        public InstructorController(ItiContext context)
        {
            itiContext = context;
        }
        
        public IActionResult Index()
        {
            ICollection<Instructor> Instructors = itiContext.Instructors.Take(100).ToList();
            return View(Instructors);
        }
        public IActionResult Details(int id)
        {
            var instructor = itiContext.Instructors.Where(s => s.InsId == id).Include(s => s.Dept).FirstOrDefault();
            var department = instructor.Dept;
            InstructorVM insVM = new InstructorVM()
            {
                InstructorName = instructor.InsName,
                InstructorDepartment = department.DeptName,
            }; 
            itiContext.SaveChanges();
            return View(insVM);
        }
        public IActionResult Create()
        {
            // return the create view to enter data
            return View();
        }
        [HttpPost]
        public IActionResult Save(Instructor ins)
        {
            if (ModelState.IsValid)
            {
                
                // create new instructor using context
                itiContext.Instructors.Add(ins);
                itiContext.SaveChanges();
            }
            return RedirectToAction("index");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var currentIns = itiContext.Instructors.Where(i =>i.InsId == id).FirstOrDefault();            
            return View(currentIns);
        }

        [HttpPost]
        public IActionResult Edit(Instructor instructor)
        {
            var currentIns = itiContext.Instructors.Where(i => i.InsId == instructor.InsId).FirstOrDefault();
            currentIns.InsName = instructor.InsName;
            currentIns.InsDegree = instructor.InsDegree;
            currentIns.Salary = instructor.Salary;            
            itiContext.SaveChanges();
            return RedirectToAction("index");
        }
        public ActionResult delete(int id) 
        {
            var currentIns = itiContext.Instructors.Where(i => i.InsId == id).FirstOrDefault();
            if (currentIns != null)
            {
                // get ins_courses for this instructor 
                var insCourses = itiContext.InsCourses.Where(c => c.InsId == id).ToList();
                // remove ins_courses for this instructor
                itiContext.InsCourses.RemoveRange(insCourses);               
                itiContext.Instructors.RemoveRange(currentIns);
                itiContext.SaveChanges();                
            }
            return RedirectToAction("index");

        }
    }
}

Views/Instructor/Create.cshtml
@model asp.netDay2.Models.Instructor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Topic</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body style="background-image:url('https://wallpapercave.com/wp/wp6684577.jpg');
   background-size: cover; background-position: center; background-repeat: no-repeat;">
    <div class="container mt-4">
        <div class="row justify-content-center">
            <div class="col-md-5">
                <h3 class="text-center" style="color:azure;">Create new instructor</h3>
                <hr style="color:aliceblue" />
                <form class="px-md-2" asp-controller="instructor" asp-action="save" method="post">

                    <div data-mdb-input-init class="form-outline mb-4">
                        @Html.LabelFor(n => n.InsId, new { @class = "form-label", style = "color: white;" })
                        @Html.TextBoxFor(n => n.InsId, new { @class = "form-control" })
                        @Html.ValidationMessageFor(n => n.InsId, "", new { @class = "text-danger" })
                    </div>
                    <div data-mdb-input-init class="form-outline mb-4">
                        @Html.LabelFor(n => n.InsName, new { @class = "form-label", style = "color: white;" })
                        @Html.TextBoxFor(n => n.InsName, new { @class = "form-control" })
                        @Html.ValidationMessageFor(n => n.InsName, "", new { @class = "text-danger" })
                    </div>
                    <div data-mdb-input-init class="form-outline mb-4">
                        @Html.LabelFor(n => n.InsDegree, new { @class = "form-label", style = "color: white;" })
                        @Html.TextBoxFor(n => n.InsDegree, new { @class = "form-control" })
                        @Html.ValidationMessageFor(n => n.InsDegree, "", new { @class = "text-danger" })
                    </div>
                    <div data-mdb-input-init class="form-outline mb-4">
                        @Html.LabelFor(n => n.Salary, new { @class = "form-label", style = "color: white;" })
                        @Html.TextBoxFor(n => n.Salary, new { @class = "form-control" })
                        @Html.ValidationMessageFor(n => n.Salary, "", new { @class = "text-danger" })
                    </div>
                    <div data-mdb-input-init class="form-outline mb-4">
                        @Html.LabelFor(n => n.DeptId, new { @class = "form-label", style = "color: white;" })
                        @Html.TextBoxFor(n => n.DeptId, new { @class = "form-control" })
                        @Html.ValidationMessageFor(n => n.DeptId, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group text-center mt-4">
                        <input type="submit" value="Submit" class="btn btn-success" />
                    </div>

                </form>
                <div class="text-center mt-3">
                    <a asp-action="Index" style="color:azure;font-size:large ;font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif">Back to List</a>
                </div>
            </div>
        </div>
    </div>
<script src="/lib/jquery/dist/jquery.min.js"></script>
<script src="/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
</body>
</html>

Views/Instructor/Details.cshtml
@model asp.netDay2.ViewModel.InstructorVM
<h1>Details</h1>
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-M3PWQaY2QFIhwuzE7VW3K1dyA0C1coQemlJD1qDzWIxmg4zFMEu50eU/HiPzGmG4" crossorigin="anonymous">
</head>
<table class="table table-striped">
    <tr style="background-color:black">
        <th style="color:azure">name</th>
        <th style="color:azure">department</th>
    </tr>
    <tr>
        <td>@Model.InstructorName</td>
        <td>@Model.InstructorDepartment</td>
         </tr>
</table>


<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgvVh5lB7Cji8gk54A1hohzTYfJr8Hd50Tvf6Ezri0fxYSl0pGr" crossorigin="anonymous"></script>

Views/Instructor/Edit.cshtml
@model asp.netDay2.Models.Instructor
@{
    var instructor = Model;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Instructor</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body style="background-image:url('https://wallpapercave.com/wp/wp6684577.jpg');
   background-size: cover; background-position: center; background-repeat: no-repeat;">
    <div class="container mt-4">
        <div class="row justify-content-center">
            <div class="col-md-5">
                <h1 class="text-center" style="color:azure;">Edit</h1>
                <h4 class="text-center" style="color:azure;">Instructor</h4>
                <hr style="color:aliceblue" />
                <form asp-controller="instructor" asp-action="edit" method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="InsId" />
                    <div class="form-group">
                        <label asp-for="InsName" class="control-label" style="color:azure; font-size:large; font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif"></label>
                        <input asp-for="InsName" class="form-control" />
                        <span asp-validation-for="InsName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="InsDegree" class="control-label" style="color:azure; font-size:large; font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif"></label>
                        <input asp-for="InsDegree" class="form-control" />
                        <span asp-validation-for="InsDegree" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Salary" class="control-label" style="color:azure; font-size:large; font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif"></label>
                        <input asp-for="Salary" class="form-control" />
                        <span asp-validation-for="Salary" class="text-danger"></span>
                    </div>
                    <div class="form-group text-center mt-4">
                        <input type="submit" value="Save" class="btn btn-primary" />
                    </div>
                </form>
                <div class="mt-3 text-center">
                    <a asp-action="Index" style="color:azure;font-size:large ;font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif">Back to List</a>
                </div>
            </div>
        </div>
    </div>

    <script src="/lib/jquery/dist/jquery.min.js"></script>
    <script src="/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
</body>
</html>

Views/Instructor/Index.cshtml
@model ICollection<asp.netDay2.Models.Instructor>
@* @{
    ViewBag.Title = "Home Page";
    Layout = "~/Views/Shared/_mylayout.cshtml";
} *@
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-M3PWQaY2QFIhwuzE7VW3K1dyA0C1coQemlJD1qDzWIxmg4zFMEu50eU/HiPzGmG4" crossorigin="anonymous">
</head>
<table class="table table-striped" style="margin-top:20px">
    <thead>
        <tr style="background-color:black">
            <th style="color:azure">
                InsID
            </th>
            <th style="color:azure">
                Name
            </th>            
            <th style="color:azure">
                InsDegree
            </th>
            <th style="color:azure">
                Dep_Id
            </th>
            <th style="color:azure">
                Salary
            </th>
            <th style="color:azure">
                Details
            </th>
            <th style="color:azure">
                Edit
            </th>
            <th style="color:azure">
                Delete
            </th>
        </tr>

    </thead>
    <tbody>
        @foreach (var instructor in Model)
        {
            <tr>
                <td>
                    @instructor.InsId
                </td>
                <td>
                    @instructor.InsName
                </td>
                <td>
                    @instructor.InsDegree
                </td>
                <td>
                    @instructor.DeptId
                </td>
                <td>
                    @instructor.Salary
                </td>
                <td>
                    <form asp-controller="instructor" asp-action="details" asp-route-id="@instructor.InsId" method="post">
                        <button  class="btn btn-info">Details</button>
                    </form>
                </td>
                <td>
                    <form asp-controller="instructor" asp-action="edit" asp-route-id="@instructor.InsId" method="get">
                        <button  class="btn btn-primary">Edit</button>
                    </form>
                </td>              
                <td>
                    <!-- Button trigger modal -->
                    <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal"
                            data-instructor-id="@instructor.InsId">
                        Delete
                    </button>

                    <!-- Modal -->
                    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">Confirm Deletion</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    Are you sure you want to delete this instructor?
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No</button>
                                    <form id="deleteForm" asp-controller="Instructor" asp-action="Delete" method="post">
                                        <!-- Hidden field to hold the instructor ID -->
                                        <input type="hidden" name="id" id="modalInstructorId">
                                        <button type="submit" class="btn btn-primary">Yes</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </td>

                <script>
                    // JavaScript to set the instructor ID in the modal form when the delete button is clicked
                    document.addEventListener('DOMContentLoaded', function () {
                        var deleteButtons = document.querySelectorAll('[data-bs-toggle="modal"]');
                        deleteButtons.forEach(function (button) {
                            button.addEventListener('click', function () {
                                var instructorId = this.getAttribute('data-instructor-id');
                                document.getElementById('modalInstructorId').value = instructorId;
                            });
                        });
                    });
                </script>
                
            </tr>
        }
        
    </tbody>
    

</table>
<form action="/instructor/create" method="post">
    <button class="btn btn-outline-primary btn-rounded" data-mdb-ripple-init data-mdb-ripple-color="dark">Create New Instructor</button>
</form>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgvVh5lB7Cji8gk54A1hohzTYfJr8Hd50Tvf6Ezri0fxYSl0pGr" crossorigin="anonymous"></script>