Models/Student.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace asp.netDay2.Models;

public partial class Student
{   
    public int StId { get; set; }
    [StringLength(50, MinimumLength = 3)]
    [Required(ErrorMessage = "First Name is required")]
    public string? StFname { get; set; }
    [StringLength(50, MinimumLength = 3)]
    [Required(ErrorMessage = "Last Name is required")]
    public string? StLname { get; set; }
    [Required(ErrorMessage = "Address is required")]
    public string? StAddress { get; set; }
    [Required(ErrorMessage = "Age is required")]
    public int? StAge { get; set; }
    [Required(ErrorMessage = "Department Id is required")]
    public int? DeptId { get; set; }

    public int? StSuper { get; set; }

    public virtual Department? Dept { get; set; }

    public virtual ICollection<Student> InverseStSuperNavigation { get; set; } = new List<Student>();

    public virtual Student? StSuperNavigation { get; set; }

    public virtual ICollection<StudCourse> StudCourses { get; set; } = new List<StudCourse>();
}

Controllers/StudentController.cs
using asp.netDay2.Models;
using asp.netDay2.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using asp.netDay2.ViewModel;
namespace asp.netDay2.Controllers
{
    public class StudentController : Controller
    {
        private readonly ItiContext itiContext;
        public StudentController(ItiContext context)
        {
            itiContext = context;
        }
        public IActionResult Index()
        {
            ICollection<Student> students = itiContext.Students.Take(100).ToList();

            return View(students);
        }        
        public IActionResult Details(int id)
        {
            var student = itiContext.Students.Where(s => s.StId == id).Include(s => s.Dept).FirstOrDefault();
            var department = student.Dept;
            StudentVM studentVM = new StudentVM()
            {
                StudentName = student.StFname + " " + student.StLname,
                StudentDepartment = department.DeptName,
                birthYear = 2024 - student.StAge
            };
            itiContext.SaveChanges();           
            return View(studentVM);
        }

        public IActionResult Create()
        {
            // return the create view to enter data
            return View();
        }

        [HttpPost]
        public IActionResult Save(Student student)
        {
            if (ModelState.IsValid)
            {
                // create new student using context
                itiContext.Students.Add(student);
                itiContext.SaveChanges();
            }
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ViewResult Edit(int id)
        {
            // 1- get student by id
            var student = itiContext.Students.Where(s => s.StId == id).FirstOrDefault();
            return View(student);
        }
        [HttpPost]
        public IActionResult Edit(Student student)
        {
            var currentStudent = itiContext.Students.Where(s => s.StId == student.StId).FirstOrDefault();
            currentStudent.StFname = student.StFname;
            currentStudent.StLname = student.StLname;            
            itiContext.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult Delete(int id)
        {
            var currentStudent = itiContext.Students.Where(s => s.StId == id).FirstOrDefault();
            if (currentStudent != null)
            {
                // get stud_courses for this student 
                var studentCourses = itiContext.StudCourses.Where(c => c.StId == id).ToList();

                // remove stud_courses for this student
                itiContext.StudCourses.RemoveRange(studentCourses);
                var students = itiContext.Students.Where(c => c.StSuper == id).ToList();
                foreach (var student in students)
                {
                    student.StSuper = null;
                    itiContext.SaveChanges();
                }
                // remove the student
                itiContext.Students.Remove(currentStudent);

                itiContext.SaveChanges();
            }

            return RedirectToAction("Index");
        }
         
    }
}

Views/Student/Create.cshtml
@model asp.netDay2.Models.Student


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Topic</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body style="background-image:url('https://wallpapercave.com/wp/wp6684577.jpg');
   background-size: cover; background-position: center; background-repeat: no-repeat;">
    <div class="container mt-4">
        <div class="row justify-content-center">
            <div class="col-md-5">
                <h3 class="text-center" style="color:azure;">Create new Student</h3>
                <hr style="color:aliceblue" />
                <form class="px-md-2" asp-controller="student" asp-action="save" method="post">

                    <div data-mdb-input-init class="form-outline mb-4">
                        @Html.LabelFor(n => n.StId, new { @class = "form-label", style = "color: white;" })
                        @Html.TextBoxFor(n => n.StId, new { @class = "form-control" })
                        @Html.ValidationMessageFor(n => n.StId, "", new { @class = "text-danger" })
                    </div>
                    <div data-mdb-input-init class="form-outline mb-4">
                        @Html.LabelFor(n => n.StFname, new { @class = "form-label", style = "color: white;" })
                        @Html.TextBoxFor(n => n.StFname, new { @class = "form-control" })
                        @Html.ValidationMessageFor(n => n.StFname, "", new { @class = "text-danger" })
                    </div>
                    <div data-mdb-input-init class="form-outline mb-4">
                        @Html.LabelFor(n => n.StLname, new { @class = "form-label", style = "color: white;" })
                        @Html.TextBoxFor(n => n.StLname, new { @class = "form-control" })
                        @Html.ValidationMessageFor(n => n.StLname, "", new { @class = "text-danger" })
                    </div>
                    <div data-mdb-input-init class="form-outline mb-4">
                        @Html.LabelFor(n => n.StAge, new { @class = "form-label", style = "color: white;" })
                        @Html.TextBoxFor(n => n.StAge, new { @class = "form-control" })
                        @Html.ValidationMessageFor(n => n.StAge, "", new { @class = "text-danger" })
                    </div>
                    <div data-mdb-input-init class="form-outline mb-4">
                        @Html.LabelFor(n => n.StAddress, new { @class = "form-label", style = "color: white;" })
                        @Html.TextBoxFor(n => n.StAddress, new { @class = "form-control" })
                        @Html.ValidationMessageFor(n => n.StAddress, "", new { @class = "text-danger" })
                    </div>
                    <div data-mdb-input-init class="form-outline mb-4">
                        @Html.LabelFor(n => n.DeptId, new { @class = "form-label", style = "color: white;" })
                        @Html.TextBoxFor(n => n.DeptId, new { @class = "form-control" })
                        @Html.ValidationMessageFor(n => n.DeptId, "", new { @class = "text-danger" })
                    </div>                    
                    <div class="form-group text-center mt-4">
                        <input type="submit" value="Submit" class="btn btn-success" />
                    </div>
                </form>
                <div class="text-center mt-3">
                    <a asp-action="Index" style="color:azure;font-size:large ;font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif">Back to List</a>
                </div>
            </div>
        </div>
    </div>
  
<script src="/lib/jquery/dist/jquery.min.js"></script>
<script src="/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
</body>
</html>

Views/Student/Details.cshtml
@model asp.netDay2.ViewModel.StudentVM
<h1>Details</h1>
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-M3PWQaY2QFIhwuzE7VW3K1dyA0C1coQemlJD1qDzWIxmg4zFMEu50eU/HiPzGmG4" crossorigin="anonymous">
</head>
<table class="table table-striped">
    <tr style="background-color:black">
        <th style="color:azure">name</th>
        <th style="color:azure">department</th>
        <th style="color:azure">birth year</th>
    </tr>
    <tr>
        <td>@Model.StudentName</td>
        <td>@Model.StudentDepartment</td>
        <td>@Model.birthYear</td>
    </tr>
</table>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgvVh5lB7Cji8gk54A1hohzTYfJr8Hd50Tvf6Ezri0fxYSl0pGr" crossorigin="anonymous"></script>

Views/Student/Edit.cshtml
@model asp.netDay2.Models.Student
@{
    var student = Model;
}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Student</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body style="background-image:url('https://wallpapercave.com/wp/wp6684577.jpg');
   background-size: cover; background-position: center; background-repeat: no-repeat;">
    <div class="container mt-4">
        <div class="row justify-content-center">
            <div class="col-md-5">
                <h1 class="text-center" style="color:azure;">Edit</h1>
                <h4 class="text-center" style="color:azure;">Student</h4>
                <hr style="color:aliceblue" />
                <form asp-controller="student" asp-action="edit" method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="StId" />
                    <div class="form-group">
                        <label asp-for="StFname" class="control-label" style="color:azure; font-size:large; font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif"></label>
                        <input asp-for="StFname" class="form-control" />
                        <span asp-validation-for="StFname" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="StLname" class="control-label" style="color:azure; font-size:large; font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif"></label>
                        <input asp-for="StLname" class="form-control" />
                        <span asp-validation-for="StLname" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="StAddress" class="control-label" style="color:azure; font-size:large; font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif"></label>
                        <input asp-for="StAddress" class="form-control" />
                        <span asp-validation-for="StAddress" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="StAge" class="control-label" style="color:azure; font-size:large; font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif"></label>
                        <input asp-for="StAge" class="form-control" />
                        <span asp-validation-for="StAge" class="text-danger"></span>
                    </div>
                    <div class="form-group text-center mt-4">
                        <input type="submit" value="Save" class="btn btn-primary" />
                    </div>
                </form>
                <div class="text-center mt-3">
                    <a asp-action="Index" style=" color:azure;font-size:large ;font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif">Back to List</a>
                </div>
            </div>
        </div>
    </div>
    <script src="/lib/jquery/dist/jquery.min.js"></script>
    <script src="/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

</body>
</html>

Views/Student/Index.cshtml
@model ICollection<asp.netDay2.Models.Student>
@* @{
    ViewBag.Title = "Home Page";
    Layout = "~/Views/Shared/_mylayout.cshtml";
} *@
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-M3PWQaY2QFIhwuzE7VW3K1dyA0C1coQemlJD1qDzWIxmg4zFMEu50eU/HiPzGmG4" crossorigin="anonymous">
</head>
<table class="table table-striped" style="margin-top:20px">
    <thead>
        <tr style="background-color:black">
            <th style="color:azure">
                ID
            </th>
            <th style="color:azure">
                Name
            </th>
            <th style="color:azure">
                Age
            </th>
            <th style="color:azure">
                Address
            </th>
            <th style="color:azure">
                Dep_Id
            </th>
            <th style="color:azure">
                Details
            </th>
            <th style="color:azure">
                Edit
            </th>
            <th style="color:azure">
                Delete
            </th>
        </tr>

    </thead>
    <tbody>
        @foreach (var student in Model)
        {
            <tr>
                <td>
                    @student.StId
                </td>
                <td>
                    @student.StFname @student.StLname
                </td>
                <td>
                    @student.StAge
                </td>
                <td>
                    @student.StAddress
                </td>
                <td>
                    @student.DeptId
                </td>
                <td>
                    <form action="/student/details/@student.StId" method="post">
                        <button  class="btn btn-info">Details</button>
                    </form>
                </td>
                <td>
                    <form asp-controller="student" asp-action="edit" asp-route-id="@student.StId" method="get">
                        <button  class="btn btn-primary">Edit</button>
                    </form>
                </td>
                <td>
                    <!-- Button trigger modal -->
                    <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal"
                            data-student-id="@student.StId">
                        Delete
                    </button>

                    <!-- Modal -->
                    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">Confirm Deletion</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    Are you sure you want to delete this student?
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No</button>
                                    <form id="deleteForm" asp-controller="Student" asp-action="Delete" method="post">
                                        <!-- Hidden field to hold the student ID -->
                                        <input type="hidden" name="id" id="modalStudentId">
                                        <button type="submit" class="btn btn-primary">Yes</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </td>

                <script>
                    // JavaScript to set the student ID in the modal form when the delete button is clicked
                    document.addEventListener('DOMContentLoaded', function () {
                        var deleteButtons = document.querySelectorAll('[data-bs-toggle="modal"]');
                        deleteButtons.forEach(function (button) {
                            button.addEventListener('click', function () {
                                var studentId = this.getAttribute('data-student-id');
                                document.getElementById('modalStudentId').value = studentId;
                            });
                        });
                    });
                </script>

               
            </tr>
        }
    </tbody>
    
</table>
<form asp-controller="student" asp-action="create" method="post">
    <button class="btn btn-outline-primary btn-rounded" data-mdb-ripple-init data-mdb-ripple-color="dark">Create New Student</button>
</form>
<script>
    //CONFIRM
</script>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgvVh5lB7Cji8gk54A1hohzTYfJr8Hd50Tvf6Ezri0fxYSl0pGr" crossorigin="anonymous"></script>