Models/Course.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace asp.netDay2.Models;

public partial class Course
{
    public int CrsId { get; set; }
    [StringLength(50, MinimumLength = 2)]
    [Required(ErrorMessage = "Name is required")]
    public string? CrsName { get; set; }
    [Required]
    public int? CrsDuration { get; set; }
    [Required]
    public int? TopId { get; set; }

    public virtual ICollection<InsCourse> InsCourses { get; set; } = new List<InsCourse>();

    public virtual ICollection<StudCourse> StudCourses { get; set; } = new List<StudCourse>();

    public virtual Topic? Top { get; set; }
}

Controllers/CourseController.cs
using asp.netDay2.Models;
using asp.netDay2.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace asp.netDay2.Controllers
{
    public class CourseController : Controller
    {
       
            private readonly ItiContext itiContext;
            public CourseController(ItiContext context)
            {
                itiContext = context;
            }
        public IActionResult Index()
        {
            ICollection<Course> Courses = itiContext.Courses.Take(100).ToList();
            return View(Courses);
        }
        public IActionResult Details(int id)
        {
            var course = itiContext.Courses.Where(s => s.CrsId == id).Include(s => s.Top).FirstOrDefault();
            var Top = course.Top;
            CourseVM crsVM = new CourseVM()
            {
                CourseName = course.CrsName,
                CourseTop = Top.TopName,
                CrsDuration =course.CrsDuration,
            };
            itiContext.SaveChanges();
            return View(crsVM);
        }
        public IActionResult Create()
        {
            // return the create view to enter data
            return View();
        }
        [HttpPost]
        public IActionResult Save(Course crs)
        {
            if (ModelState.IsValid)
            {

                // create new instructor using context
                itiContext.Courses.Add(crs);
                itiContext.SaveChanges();
            }
            return RedirectToAction("index");
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var currentCrs = itiContext.Courses.Where(c => c.CrsId == id).FirstOrDefault();
            return View(currentCrs);
        }
        [HttpPost]
        public IActionResult Edit(Course crs)
        {
            var currentcrs = itiContext.Courses.Where(c => c.CrsId == crs.CrsId).FirstOrDefault();
            currentcrs.CrsName = crs.CrsName;
            currentcrs.CrsDuration = crs.CrsDuration;
            currentcrs.TopId = crs.TopId;
            itiContext.SaveChanges();
            return RedirectToAction("index");
        }
        public ActionResult delete(int id)
        {
            var currentCrs = itiContext.Courses.Where(c => c.CrsId == id).FirstOrDefault();
            if (currentCrs != null)
            {
                // get ins_courses for this instructor 
                //var topCourses = itiContext.Topics.Where(c => c.TopId == id).ToList();
                // remove ins_courses for this instructor
                //itiContext.Topics.RemoveRange(topCourses);
                itiContext.Courses.RemoveRange(currentCrs);
                itiContext.SaveChanges();
            }
            return RedirectToAction("index");

        }
    }
}

Views/Course/Create.cshtml
@model asp.netDay2.Models.Course

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Topic</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body style="background-image:url('https://wallpapercave.com/wp/wp6684577.jpg');
   background-size: cover; background-position: center; background-repeat: no-repeat;">
    <div class="container mt-4">
        <div class="row justify-content-center">
            <div class="col-md-5">
                <h3 class="text-center" style="color:azure;">Create new Course</h3>
                <hr style="color:aliceblue" />
                <form class="px-md-2" asp-controller="course" asp-action="save" method="post">

                    <div data-mdb-input-init class="form-outline mb-4">
                        @Html.LabelFor(n => n.CrsId, new { @class = "form-label", style = "color: white;" })
                        @Html.TextBoxFor(n => n.CrsId, new { @class = "form-control" })
                        @Html.ValidationMessageFor(n => n.CrsId, "", new { @class = "text-danger" })
                    </div>
                    <div data-mdb-input-init class="form-outline mb-4">
                        @Html.LabelFor(n => n.CrsName, new { @class = "form-label", style = "color: white;" })
                        @Html.TextBoxFor(n => n.CrsName, new { @class = "form-control" })
                        @Html.ValidationMessageFor(n => n.CrsName, "", new { @class = "text-danger" })
                    </div>
                    <div data-mdb-input-init class="form-outline mb-4">
                        @Html.LabelFor(n => n.CrsDuration, new { @class = "form-label", style = "color: white;" })
                        @Html.TextBoxFor(n => n.CrsDuration, new { @class = "form-control" })
                        @Html.ValidationMessageFor(n => n.CrsDuration, "", new { @class = "text-danger" })
                    </div>
                    <div data-mdb-input-init class="form-outline mb-4">
                        @Html.LabelFor(n => n.TopId, new { @class = "form-label", style = "color: white;" })
                        @Html.TextBoxFor(n => n.TopId, new { @class = "form-control" })
                        @Html.ValidationMessageFor(n => n.TopId, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group text-center mt-4">
                        <input type="submit" value="Submit" class="btn btn-success" />
                    </div>
                </form>
                <div class="text-center mt-3">
                    <a asp-action="Index" style="color:azure;font-size:large ;font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif">Back to List</a>
                </div>
            </div>
        </div>
    </div>
 
<script src="/lib/jquery/dist/jquery.min.js"></script>
<script src="/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
</body>
</html>

Views/Course/Details.cshtml
@model asp.netDay2.ViewModel.CourseVM
<h1>Details</h1>
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-M3PWQaY2QFIhwuzE7VW3K1dyA0C1coQemlJD1qDzWIxmg4zFMEu50eU/HiPzGmG4" crossorigin="anonymous">
</head>
<table class="table table-striped">
    <tr style ="background-color:black">
        <th style="color:azure">CourseName</th>
        <th style="color:azure">CrsDuration</th>
        <th style="color:azure">CourseTop</th>
    </tr>
    <tr>
        <td>@Model.CourseName</td>
        <td>@Model.CrsDuration</td>
        <td>@Model.CourseTop</td>
    </tr>
</table>


<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgvVh5lB7Cji8gk54A1hohzTYfJr8Hd50Tvf6Ezri0fxYSl0pGr" crossorigin="anonymous"></script>

Views/Course/Edit.cshtml
@model asp.netDay2.Models.Course
@{
    var crs = Model;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Instructor</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body style="background-image:url('https://wallpapercave.com/wp/wp6684577.jpg');
   background-size: cover; background-position: center; background-repeat: no-repeat;">
    <div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-5">
                <h1 class="text-center" style="color:azure;">Edit</h1>
                <h4 class="text-center" style="color:azure;">Course</h4>
                <hr style="color:aliceblue" />
            <form asp-controller="course" asp-action="edit" method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="CrsId" />
                <div class="form-group">
                    <label asp-for="CrsName" class="control-label" style="color:azure; font-size:large; font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif"></label>
                    <input asp-for="CrsName" class="form-control" />
                    <span asp-validation-for="CrsName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="CrsDuration" class="control-label" style="color:azure; font-size:large; font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif"></label>
                    <input asp-for="CrsDuration" class="form-control" />
                    <span asp-validation-for="CrsDuration" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="TopId" class="control-label" style="color:azure; font-size:large; font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif"></label>
                    <input asp-for="TopId" class="form-control" />
                    <span asp-validation-for="TopId" class="text-danger"></span>
                </div>
                <div class="form-group text-center mt-4">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
            </form>
            <div class="text-center mt-3 ">
                    <a asp-action="Index" style=" color:azure;font-size:large ;font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif">Back to List</a>
            </div>

        </div>
    </div>
</div>

<script src="/lib/jquery/dist/jquery.min.js"></script>
<script src="/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
</body>
</html>



                  

Views/Course/Index.cshtml
@model ICollection<asp.netDay2.Models.Course>
@* @{
    ViewBag.Title = "Home Page";
    Layout = "~/Views/Shared/_mylayout.cshtml";
} *@




<head>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-M3PWQaY2QFIhwuzE7VW3K1dyA0C1coQemlJD1qDzWIxmg4zFMEu50eU/HiPzGmG4" crossorigin="anonymous">
</head>

<table class="table table-striped" style="margin-top:20px">
    <thead>
        <tr style="background-color:black">
            <th style="color:azure">
                crsID
            </th>
            <th style="color:azure">
                Name
            </th>
            <th style="color:azure">
                CrsDuration
            </th>
            <th style="color:azure">
                TopId
            </th> 
            <th style="color:azure">
                Details
            </th>
            <th style="color:azure">
                Edit
            </th>
            <th style="color:azure">
                Delete
            </th>
        </tr>

    </thead>
    <tbody>
        @foreach (var crs in Model)
        {
            <tr>
                <td>
                    @crs.CrsId
                </td>
                <td>
                    @crs.CrsName
                </td>
                <td>
                    @crs.CrsDuration
                </td>
                <td>
                    @crs.TopId
                </td> 
                
                <td>
                    <form asp-controller="course" asp-action="details" asp-route-id="@crs.CrsId" method="post">
                        <button  class="btn btn-info">Details</button>
                    </form>
                </td>
                <td>
                    <form asp-controller="course" asp-action="edit" asp-route-id="@crs.CrsId" method="get">
                        <button  class="btn btn-primary">Edit</button>
                    </form>
                </td>
                <td>
                    <!-- Button trigger modal -->
                    <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal"
                            data-course-id="@crs.CrsId">
                        Delete
                    </button>

                    <!-- Modal -->
                    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">Confirm Deletion</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    Are you sure you want to delete this course?
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No</button>
                                    <form id="deleteForm" asp-controller="Course" asp-action="Delete" method="post">
                                        <!-- Hidden field to hold the course ID -->
                                        <input type="hidden" name="id" id="modalCourseId">
                                        <button type="submit" class="btn btn-primary">Yes</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </td>

                <script>
                    // JavaScript to set the course ID in the modal form when the delete button is clicked
                    document.addEventListener('DOMContentLoaded', function () {
                        var deleteButtons = document.querySelectorAll('[data-bs-toggle="modal"]');
                        deleteButtons.forEach(function (button) {
                            button.addEventListener('click', function () {
                                var courseId = this.getAttribute('data-course-id');
                                document.getElementById('modalCourseId').value = courseId;
                            });
                        });
                    });
                </script>


            </tr>                
        }           
    </tbody>   
</table>  
        <form action="/course/create" method="post">
        <button class="btn btn-outline-primary btn-rounded" data-mdb-ripple-init data-mdb-ripple-color="dark">Create New Course</button>
        </form>   

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgvVh5lB7Cji8gk54A1hohzTYfJr8Hd50Tvf6Ezri0fxYSl0pGr" crossorigin="anonymous"></script>